export const products = [
  {
    id: 1,
    title: "CHEESBURGUER",
    price: 20500,
    stock: 5,
    description: "200grs de Carne - Cheddar - Panceta - Tomate - 2 Salsas a eleccion",
    category: "hambur",
    img: "https://res.cloudinary.com/dcm170r29/image/upload/v1675870381/ches_cdd4wl.webp",
  },
  {
    id: 2,
    title: "COMADNA",
    price: 14500,
    stock: 5,
    description: "200grs de Carne - Provolone - Cebolla caramelizada - Panceta - Tomate - 2 Salsas a eleccion",
    category: "hambur",
    img: "https://res.cloudinary.com/dcm170r29/image/upload/v1675870381/comanda_aiotcc.webp",
  },
  {
    id: 3,
    title: "Pollo Crispy",
    price: 19000,
    stock: 5,
    description:
      "Medallon de Pollo Crispy - Cheddar - Rucula - Tomate - 2 Salsas a eleccion",
    category: "hambur",
    img: "https://res.cloudinary.com/dcm170r29/image/upload/v1675870381/pollo_iodzps.webp",
  },
  {
    id: 4,
    title: "CLASICA",
    price: 17800,
    stock: 5,
    description: "200grms de Carne - Jamon Muzzarella - Panceta - Tomate - 2 Salsas a eleccion",
    category: "hambur",
    img: "https://res.cloudinary.com/dcm170r29/image/upload/v1675870382/CLASICA_h244bt.png",
  },
  {
    id: 6,
    title: "De Espinaca",
    price: 17800,
    stock: 5,
    description: "Doble medallon de espinaca, Queso Cheddar, Tomate, Rucula, 2 salsas a eleccion",
    category: "veggie",
    img: "https://res.cloudinary.com/dcm170r29/image/upload/v1675954573/espi_b1hkg8.jpg",
  },
  {
    id: 7,
    title: "De Znahoria y Puerro",
    price: 17800,
    stock: 5,
    description: "Mdallon de zanahoria y puerro, Muzzarella, Tomate, Rucula, 2 salsas a eleccion",
    category: "veggie",
    img: "https://res.cloudinary.com/dcm170r29/image/upload/v1675954573/zyp_cbsx0s.png",
  },
  {
    id: 8,
    title: "De Lentejas",
    price: 17800,
    stock: 5,
    description: "Mdallon de lenteja, Muzzarella, Tomate, Rucula, 2 salsas a eleccion",
    category: "veggie",
    img: "https://res.cloudinary.com/dcm170r29/image/upload/v1675954573/len_naqdmz.png",
  },
  {
    id: 9,
    title: "Beyond Burguer",
    price: 17800,
    stock: 5,
    description: "Queso cheddar, Cebolla caramelizada, Tomate, Rucula y 2 salsas a eleccion",
    category: "veggie",
    img: "https://res.cloudinary.com/dcm170r29/image/upload/v1675954573/len_naqdmz.png",
  }
];
